Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "ubuntu20"
  config.vm.provider :virtualbox do |v|
    v.name = "ubuntu20"
    v.memory = 512
    v.cpus = 1
  config.vm.network :private_network, ip: "192.168.56.3"
  config.vm.network "forwarded_port", guest: 80, host: 8080
end
end
