Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "ubuntu22"
  config.vm.provider :virtualbox do |v|
    v.name = "ubuntu22"
    v.memory = 512
    v.cpus = 1
  config.vm.network :private_network, ip: "192.168.56.3"  
  end 
end
