Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "base"
  config.vm.provision "ansible", playbook: "playbook.yml"
  config.vm.provider :virtualbox do |v|
    v.name = "base"
    v.memory = 512
    v.cpus = 1
  end 
end
