Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "hugo"
  config.vm.provision "ansible", playbook: "playbook.yml"
  config.vm.provider :virtualbox do |v|
    v.name = "hugo"
    v.memory = 512
    v.cpus = 1
  config.vm.network :private_network, ip: "192.168.56.3"
  config.vm.network "forwarded_port", guest: 80, host: 8080
end
end
