Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "centos7"
    config.vm.provider :virtualbox do |v|
      v.name = "centos7"
      v.memory = 512
      v.cpus = 1
    config.vm.network :private_network, ip: "192.168.56.3"
  end
end
